workflows:
  native-android:
    name: Testing Application
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      java: 17
      android_signing:
        - Testing App
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.example.testingapplication"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'uat'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release
        script: |
          ./gradlew bundleRelease
    artifacts:
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - gayanmadushanka541@gmail.com
        notify:
          success: true
          failure: false
